version: '3'
services:
  mysql:
    image: mysql:9-oracle
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=moov
      - MYSQL_USER=moov
      - MYSQL_PASSWORD=moov
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - intranet
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    tmpfs: # Run this mysql in memory as its used for testing
      - /var/lib/mysql

  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
    restart: always
    ports:
      - "9010:9010"
      - "9020:9020"
    networks:
      - intranet

  alloydb:
    image: google/alloydbomni
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=moov
      - POSTGRES_USER=moov
      - POSTGRES_PASSWORD=moov
      - POSTGRES_DATABASE=moov
    networks:
      - intranet
    tmpfs:
      - /var/lib/postgresql/data

networks:
  intranet:
